/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package org.universAAL.lddi.lib.ieeex73std.x73.p20601.dim;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.LinkedList;

/**
 * Subclauses 6.3.2 through 6.3.9 describe the classes of the personal health
 * device DIM. Each subclause uses the following format: - The nomenclature code
 * used to identify the class. This code is used during the configuration event
 * to report the class for each object and allows the manager to learn whether
 * the object being specified is numeric, RT-SA, or any of the other classes. -
 * The attributes defined by the class. - The methods available. - The potential
 * events generated by objects instantiated from the class. - The available
 * services such as getting or setting attributes.
 * 
 * @author lgigante
 *
 */
public abstract class DIM {

	protected Hashtable<Integer, Object> objects;

	public DIM() {

		objects = new Hashtable<Integer, Object>(); // Handle | Numeric

	}

	public void addObjecttoDim(int handle, Object obj) {
		objects.put(handle, obj);
	}

	public Object getObjectfromDim(int handle) {
		return objects.get(handle);
	}

	public abstract int getNomenclatureCode();

}
