
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PmSegmentEntryMap", isSet = false )
    public class PmSegmentEntryMap implements IASN1PreparedElement {
            
        @ASN1Element ( name = "segm-entry-header", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SegmEntryHeader segm_entry_header = null;
                
  
        @ASN1Element ( name = "segm-entry-elem-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SegmEntryElemList segm_entry_elem_list = null;
                
  
        
        public SegmEntryHeader getSegm_entry_header () {
            return this.segm_entry_header;
        }

        

        public void setSegm_entry_header (SegmEntryHeader value) {
            this.segm_entry_header = value;
        }
        
  
        
        public SegmEntryElemList getSegm_entry_elem_list () {
            return this.segm_entry_elem_list;
        }

        

        public void setSegm_entry_elem_list (SegmEntryElemList value) {
            this.segm_entry_elem_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PmSegmentEntryMap.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            