
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "SegmentDataEvent", isSet = false )
    public class SegmentDataEvent implements IASN1PreparedElement {
            
        @ASN1Element ( name = "segm-data-event-descr", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SegmDataEventDescr segm_data_event_descr = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "segm-data-event-entries", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] segm_data_event_entries = null;
                
  
        
        public SegmDataEventDescr getSegm_data_event_descr () {
            return this.segm_data_event_descr;
        }

        

        public void setSegm_data_event_descr (SegmDataEventDescr value) {
            this.segm_data_event_descr = value;
        }
        
  
        
        public byte[] getSegm_data_event_entries () {
            return this.segm_data_event_entries;
        }

        

        public void setSegm_data_event_entries (byte[] value) {
            this.segm_data_event_entries = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SegmentDataEvent.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            