@ECHO OFF
ECHO removing old 'bundles' folder ...
RMDIR /s /q "runner\bundles"
ECHO removing old 'log' folder ...
RMDIR /s /q "runner\log"
@ECHO OFF
ECHO removing old 'cache' folder ...
RMDIR /s /q "runner\cache"
ECHO removing old 'felix\cache' folder ...
RMDIR /s /q "runner\felix\cache"
ECHO removing old 'felix\config.ini' file ...
DEL "runner\felix\config.ini"
ECHO removing old 'deploy-pom.xml' file ...
DEL "runner\deploy-pom.xml"

PAUSE