
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AareApdu", isSet = false )
    public class AareApdu implements IASN1PreparedElement {
            
        @ASN1Element ( name = "result", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AssociateResult result = null;
                
  
        @ASN1Element ( name = "selected-data-proto", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DataProto selected_data_proto = null;
                
  
        
        public AssociateResult getResult () {
            return this.result;
        }

        

        public void setResult (AssociateResult value) {
            this.result = value;
        }
        
  
        
        public DataProto getSelected_data_proto () {
            return this.selected_data_proto;
        }

        

        public void setSelected_data_proto (DataProto value) {
            this.selected_data_proto = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AareApdu.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            