
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AbsTimeRange", isSet = false )
    public class AbsTimeRange implements IASN1PreparedElement {
            
        @ASN1Element ( name = "from-time", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AbsoluteTime from_time = null;
                
  
        @ASN1Element ( name = "to-time", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AbsoluteTime to_time = null;
                
  
        
        public AbsoluteTime getFrom_time () {
            return this.from_time;
        }

        

        public void setFrom_time (AbsoluteTime value) {
            this.from_time = value;
        }
        
  
        
        public AbsoluteTime getTo_time () {
            return this.to_time;
        }

        

        public void setTo_time (AbsoluteTime value) {
            this.to_time = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AbsTimeRange.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            