
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ObservationScanFixed", isSet = false )
    public class ObservationScanFixed implements IASN1PreparedElement {
            
        @ASN1Element ( name = "obj-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HANDLE obj_handle = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "obs-val-data", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] obs_val_data = null;
                
  
        
        public HANDLE getObj_handle () {
            return this.obj_handle;
        }

        

        public void setObj_handle (HANDLE value) {
            this.obj_handle = value;
        }
        
  
        
        public byte[] getObs_val_data () {
            return this.obs_val_data;
        }

        

        public void setObs_val_data (byte[] value) {
            this.obs_val_data = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ObservationScanFixed.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            