/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ProdSpecEntry", isSet = false )
    public class ProdSpecEntry implements IASN1PreparedElement {

    	@ASN1Element ( name = "spec-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 spec_type = null;
                
  
        @ASN1Element ( name = "component-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid component_id = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "prod-spec", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] prod_spec = null;
                
  
        
        public INT_U16 getSpec_type () {
            return this.spec_type;
        }

        

        public void setSpec_type (INT_U16 value) {
            this.spec_type = value;
        }
        
  
        
        public PrivateOid getComponent_id () {
            return this.component_id;
        }

        

        public void setComponent_id (PrivateOid value) {
            this.component_id = value;
        }
        
  
        
        public byte[] getProd_spec () {
            return this.prod_spec;
        }

        

        public void setProd_spec (byte[] value) {
            this.prod_spec = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ProdSpecEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            