
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "SegmentStatistics" )
    public class SegmentStatistics implements IASN1PreparedElement {
                
            
            @ASN1SequenceOf( name = "SegmentStatistics" , isSetOf = false)
	    private java.util.Collection<SegmentStatisticEntry> value = null; 
    
            public SegmentStatistics () {
            }
        
            public SegmentStatistics ( java.util.Collection<SegmentStatisticEntry> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<SegmentStatisticEntry> value) {
                this.value = value;
            }
            
            public java.util.Collection<SegmentStatisticEntry> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<SegmentStatisticEntry>()); 
            }
            
            public void add(SegmentStatisticEntry item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SegmentStatistics.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            