/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "SegmDataEventDescr", isSet = false )
    public class SegmDataEventDescr implements IASN1PreparedElement {
            
        @ASN1Element ( name = "segm-instance", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InstNumber segm_instance = null;
                
  
        @ASN1Element ( name = "segm-evt-entry-index", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 segm_evt_entry_index = null;
                
  
        @ASN1Element ( name = "segm-evt-entry-count", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 segm_evt_entry_count = null;
                
  
        @ASN1Element ( name = "segm-evt-status", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SegmEvtStatus segm_evt_status = null;
                
  
        
        public InstNumber getSegm_instance () {
            return this.segm_instance;
        }

        

        public void setSegm_instance (InstNumber value) {
            this.segm_instance = value;
        }
        
  
        
        public INT_U32 getSegm_evt_entry_index () {
            return this.segm_evt_entry_index;
        }

        

        public void setSegm_evt_entry_index (INT_U32 value) {
            this.segm_evt_entry_index = value;
        }
        
  
        
        public INT_U32 getSegm_evt_entry_count () {
            return this.segm_evt_entry_count;
        }

        

        public void setSegm_evt_entry_count (INT_U32 value) {
            this.segm_evt_entry_count = value;
        }
        
  
        
        public SegmEvtStatus getSegm_evt_status () {
            return this.segm_evt_status;
        }

        

        public void setSegm_evt_status (SegmEvtStatus value) {
            this.segm_evt_status = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SegmDataEventDescr.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            