/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_universAAL_continua_weighingscale_publisher_hdpManager */

#ifndef _Included_org_universAAL_continua_weighingscale_publisher_hdpManager
#define _Included_org_universAAL_continua_weighingscale_publisher_hdpManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    startDbusPlatform
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_startDbusPlatform
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getLocalBluetoothAdapterPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getLocalBluetoothAdapterPath
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    showLocalBluetoothAdaptersPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_showLocalBluetoothAdaptersPath
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    showDefaultLocalBluetoothAdaptersProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_showDefaultLocalBluetoothAdaptersProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getRemoteBluetoothAdapterPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getRemoteBluetoothAdapterPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    showRemoteBluetoothAdapterProperties
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_showRemoteBluetoothAdapterProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    setPropertyRemoteDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_setPropertyRemoteDevice
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    createHDPApplication
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_createHDPApplication
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    destroyHDPApplication
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_destroyHDPApplication
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getDbusSystemAvailability
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getDbusSystemAvailability
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    enableHDPListener
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_enableHDPListener
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    waitHDPConnections
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_waitHDPConnections
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getHDPDataChannelPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getHDPDataChannelPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    showHDPDataChannelProperties
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_showHDPDataChannelProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getHDPDataChannelFileDescriptor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getHDPDataChannelFileDescriptor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    releaseHDPDataChannelFileDescriptor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_releaseHDPDataChannelFileDescriptor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    waitHDPDataFrames
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_waitHDPDataFrames
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getHDPDataFrame
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getHDPDataFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    getSizeHDPDataFrame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_getSizeHDPDataFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    showHDPDataFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_showHDPDataFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    sendHDPDataToDevice
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_sendHDPDataToDevice
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     org_universAAL_continua_weighingscale_publisher_hdpManager
 * Method:    closeHDPManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_universAAL_continua_weighingscale_publisher_hdpManager_closeHDPManager
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
