
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DataReqModeCapab", isSet = false )
    public class DataReqModeCapab implements IASN1PreparedElement {
            
        @ASN1Element ( name = "data-req-mode-flags", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DataReqModeFlags data_req_mode_flags = null;
                
  
        @ASN1Element ( name = "data-req-init-agent-count", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 data_req_init_agent_count = null;
                
  
        @ASN1Element ( name = "data-req-init-manager-count", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 data_req_init_manager_count = null;
                
  
        
        public DataReqModeFlags getData_req_mode_flags () {
            return this.data_req_mode_flags;
        }

        

        public void setData_req_mode_flags (DataReqModeFlags value) {
            this.data_req_mode_flags = value;
        }
        
  
        
        public INT_U8 getData_req_init_agent_count () {
            return this.data_req_init_agent_count;
        }

        

        public void setData_req_init_agent_count (INT_U8 value) {
            this.data_req_init_agent_count = value;
        }
        
  
        
        public INT_U8 getData_req_init_manager_count () {
            return this.data_req_init_manager_count;
        }

        

        public void setData_req_init_manager_count (INT_U8 value) {
            this.data_req_init_manager_count = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DataReqModeCapab.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            