
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "RejectResult", isSet = false )
    public class RejectResult implements IASN1PreparedElement {
            
        @ASN1Element ( name = "problem", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RorjProblem problem = null;
                
  
        
        public RorjProblem getProblem () {
            return this.problem;
        }

        

        public void setProblem (RorjProblem value) {
            this.problem = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RejectResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            