
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ScanReportPerGrouped", isSet = false )
    public class ScanReportPerGrouped implements IASN1PreparedElement {
            
        @ASN1Element ( name = "person-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PersonId person_id = null;
                
  
        @ASN1Element ( name = "obs-scan-grouped", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ObservationScanGrouped obs_scan_grouped = null;
                
  
        
        public PersonId getPerson_id () {
            return this.person_id;
        }

        

        public void setPerson_id (PersonId value) {
            this.person_id = value;
        }
        
  
        
        public ObservationScanGrouped getObs_scan_grouped () {
            return this.obs_scan_grouped;
        }

        

        public void setObs_scan_grouped (ObservationScanGrouped value) {
            this.obs_scan_grouped = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ScanReportPerGrouped.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            