
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TypeVer", isSet = false )
    public class TypeVer implements IASN1PreparedElement {
            
        @ASN1Element ( name = "type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type type = null;
                
        @ASN1Element ( name = "version", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 version = null;
                
  
        
        public OID_Type getType () {
            return this.type;
        }

        

        public void setType (OID_Type value) {
            this.type = value;
        }
        
  
        
        public INT_U16 getVersion () {
            return this.version;
        }

        

        public void setVersion (INT_U16 value) {
            this.version = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TypeVer.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            