/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package org.universAAL.lddi.lib.ieeex73std.x73.p20601;
//

// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.universAAL.lddi.lib.ieeex73std.org.bn.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.constraints.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.coders.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.types.*;

@ASN1PreparedElement
@ASN1Sequence(name = "ActionResultSimple", isSet = false)
public class ActionResultSimple implements IASN1PreparedElement {

	@ASN1Element(name = "obj-handle", isOptional = false, hasTag = false, hasDefaultValue = false)

	private HANDLE obj_handle = null;

	@ASN1Element(name = "action-type", isOptional = false, hasTag = false, hasDefaultValue = false)

	private OID_Type action_type = null;

	@ASN1Any(name = "")

	@ASN1Element(name = "action-info-args", isOptional = false, hasTag = false, hasDefaultValue = false)

	private byte[] action_info_args = null;

	public HANDLE getObj_handle() {
		return this.obj_handle;
	}

	public void setObj_handle(HANDLE value) {
		this.obj_handle = value;
	}

	public OID_Type getAction_type() {
		return this.action_type;
	}

	public void setAction_type(OID_Type value) {
		this.action_type = value;
	}

	public byte[] getAction_info_args() {
		return this.action_info_args;
	}

	public void setAction_info_args(byte[] value) {
		this.action_info_args = value;
	}

	public void initWithDefaults() {

	}

	private static IASN1PreparedElementData preparedData = CoderFactory.getInstance()
			.newPreparedElementData(ActionResultSimple.class);

	public IASN1PreparedElementData getPreparedData() {
		return preparedData;
	}

}
