/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package org.universAAL.lddi.lib.ieeex73std.x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.universAAL.lddi.lib.ieeex73std.org.bn.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.constraints.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.coders.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DataApdu", isSet = false )
    public class DataApdu implements IASN1PreparedElement {
            
        @ASN1Element ( name = "invoke-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InvokeIDType invoke_id = null;
                
  
        
    @ASN1PreparedElement
    @ASN1Choice ( name = "message" )
    public static class MessageChoiceType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "roiv-cmip-event-report", isOptional =  false , hasTag =  true, tag = 256 , hasDefaultValue =  false  )
    
	private EventReportArgumentSimple roiv_cmip_event_report = null;
                
  
        @ASN1Element ( name = "roiv-cmip-confirmed-event-report", isOptional =  false , hasTag =  true, tag = 257 , hasDefaultValue =  false  )
    
	private EventReportArgumentSimple roiv_cmip_confirmed_event_report = null;
                
  
        @ASN1Element ( name = "roiv-cmip-get", isOptional =  false , hasTag =  true, tag = 259 , hasDefaultValue =  false  )
    
	private GetArgumentSimple roiv_cmip_get = null;
                
  
        @ASN1Element ( name = "roiv-cmip-set", isOptional =  false , hasTag =  true, tag = 260 , hasDefaultValue =  false  )
    
	private SetArgumentSimple roiv_cmip_set = null;
                
  
        @ASN1Element ( name = "roiv-cmip-confirmed-set", isOptional =  false , hasTag =  true, tag = 261 , hasDefaultValue =  false  )
    
	private SetArgumentSimple roiv_cmip_confirmed_set = null;
                
  
        @ASN1Element ( name = "roiv-cmip-action", isOptional =  false , hasTag =  true, tag = 262 , hasDefaultValue =  false  )
    
	private ActionArgumentSimple roiv_cmip_action = null;
                
  
        @ASN1Element ( name = "roiv-cmip-confirmed-action", isOptional =  false , hasTag =  true, tag = 263 , hasDefaultValue =  false  )
    
	private ActionArgumentSimple roiv_cmip_confirmed_action = null;
                
  
        @ASN1Element ( name = "rors-cmip-confirmed-event-report", isOptional =  false , hasTag =  true, tag = 513 , hasDefaultValue =  false  )
    
	private EventReportResultSimple rors_cmip_confirmed_event_report = null;
                
  
        @ASN1Element ( name = "rors-cmip-get", isOptional =  false , hasTag =  true, tag = 515 , hasDefaultValue =  false  )
    
	private GetResultSimple rors_cmip_get = null;
                
  
        @ASN1Element ( name = "rors-cmip-confirmed-set", isOptional =  false , hasTag =  true, tag = 517 , hasDefaultValue =  false  )
    
	private SetResultSimple rors_cmip_confirmed_set = null;
                
  
        @ASN1Element ( name = "rors-cmip-confirmed-action", isOptional =  false , hasTag =  true, tag = 519 , hasDefaultValue =  false  )
    
	private ActionResultSimple rors_cmip_confirmed_action = null;
                
  
        @ASN1Element ( name = "roer", isOptional =  false , hasTag =  true, tag = 768 , hasDefaultValue =  false  )
    
	private ErrorResult roer = null;
                
  
        @ASN1Element ( name = "rorj", isOptional =  false , hasTag =  true, tag = 1024 , hasDefaultValue =  false  )
    
	private RejectResult rorj = null;
                
  
        
        public EventReportArgumentSimple getRoiv_cmip_event_report () {
            return this.roiv_cmip_event_report;
        }

        public boolean isRoiv_cmip_event_reportSelected () {
            return this.roiv_cmip_event_report != null;
        }

        private void setRoiv_cmip_event_report (EventReportArgumentSimple value) {
            this.roiv_cmip_event_report = value;
        }

        
        public void selectRoiv_cmip_event_report (EventReportArgumentSimple value) {
            this.roiv_cmip_event_report = value;
            
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public EventReportArgumentSimple getRoiv_cmip_confirmed_event_report () {
            return this.roiv_cmip_confirmed_event_report;
        }

        public boolean isRoiv_cmip_confirmed_event_reportSelected () {
            return this.roiv_cmip_confirmed_event_report != null;
        }

        private void setRoiv_cmip_confirmed_event_report (EventReportArgumentSimple value) {
            this.roiv_cmip_confirmed_event_report = value;
        }

        
        public void selectRoiv_cmip_confirmed_event_report (EventReportArgumentSimple value) {
            this.roiv_cmip_confirmed_event_report = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public GetArgumentSimple getRoiv_cmip_get () {
            return this.roiv_cmip_get;
        }

        public boolean isRoiv_cmip_getSelected () {
            return this.roiv_cmip_get != null;
        }

        private void setRoiv_cmip_get (GetArgumentSimple value) {
            this.roiv_cmip_get = value;
        }

        
        public void selectRoiv_cmip_get (GetArgumentSimple value) {
            this.roiv_cmip_get = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public SetArgumentSimple getRoiv_cmip_set () {
            return this.roiv_cmip_set;
        }

        public boolean isRoiv_cmip_setSelected () {
            return this.roiv_cmip_set != null;
        }

        private void setRoiv_cmip_set (SetArgumentSimple value) {
            this.roiv_cmip_set = value;
        }

        
        public void selectRoiv_cmip_set (SetArgumentSimple value) {
            this.roiv_cmip_set = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public SetArgumentSimple getRoiv_cmip_confirmed_set () {
            return this.roiv_cmip_confirmed_set;
        }

        public boolean isRoiv_cmip_confirmed_setSelected () {
            return this.roiv_cmip_confirmed_set != null;
        }

        private void setRoiv_cmip_confirmed_set (SetArgumentSimple value) {
            this.roiv_cmip_confirmed_set = value;
        }

        
        public void selectRoiv_cmip_confirmed_set (SetArgumentSimple value) {
            this.roiv_cmip_confirmed_set = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public ActionArgumentSimple getRoiv_cmip_action () {
            return this.roiv_cmip_action;
        }

        public boolean isRoiv_cmip_actionSelected () {
            return this.roiv_cmip_action != null;
        }

        private void setRoiv_cmip_action (ActionArgumentSimple value) {
            this.roiv_cmip_action = value;
        }

        
        public void selectRoiv_cmip_action (ActionArgumentSimple value) {
            this.roiv_cmip_action = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public ActionArgumentSimple getRoiv_cmip_confirmed_action () {
            return this.roiv_cmip_confirmed_action;
        }

        public boolean isRoiv_cmip_confirmed_actionSelected () {
            return this.roiv_cmip_confirmed_action != null;
        }

        private void setRoiv_cmip_confirmed_action (ActionArgumentSimple value) {
            this.roiv_cmip_confirmed_action = value;
        }

        
        public void selectRoiv_cmip_confirmed_action (ActionArgumentSimple value) {
            this.roiv_cmip_confirmed_action = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public EventReportResultSimple getRors_cmip_confirmed_event_report () {
            return this.rors_cmip_confirmed_event_report;
        }

        public boolean isRors_cmip_confirmed_event_reportSelected () {
            return this.rors_cmip_confirmed_event_report != null;
        }

        private void setRors_cmip_confirmed_event_report (EventReportResultSimple value) {
            this.rors_cmip_confirmed_event_report = value;
        }

        
        public void selectRors_cmip_confirmed_event_report (EventReportResultSimple value) {
            this.rors_cmip_confirmed_event_report = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public GetResultSimple getRors_cmip_get () {
            return this.rors_cmip_get;
        }

        public boolean isRors_cmip_getSelected () {
            return this.rors_cmip_get != null;
        }

        private void setRors_cmip_get (GetResultSimple value) {
            this.rors_cmip_get = value;
        }

        
        public void selectRors_cmip_get (GetResultSimple value) {
            this.rors_cmip_get = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public SetResultSimple getRors_cmip_confirmed_set () {
            return this.rors_cmip_confirmed_set;
        }

        public boolean isRors_cmip_confirmed_setSelected () {
            return this.rors_cmip_confirmed_set != null;
        }

        private void setRors_cmip_confirmed_set (SetResultSimple value) {
            this.rors_cmip_confirmed_set = value;
        }

        
        public void selectRors_cmip_confirmed_set (SetResultSimple value) {
            this.rors_cmip_confirmed_set = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public ActionResultSimple getRors_cmip_confirmed_action () {
            return this.rors_cmip_confirmed_action;
        }

        public boolean isRors_cmip_confirmed_actionSelected () {
            return this.rors_cmip_confirmed_action != null;
        }

        private void setRors_cmip_confirmed_action (ActionResultSimple value) {
            this.rors_cmip_confirmed_action = value;
        }

        
        public void selectRors_cmip_confirmed_action (ActionResultSimple value) {
            this.rors_cmip_confirmed_action = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRoer(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public ErrorResult getRoer () {
            return this.roer;
        }

        public boolean isRoerSelected () {
            return this.roer != null;
        }

        private void setRoer (ErrorResult value) {
            this.roer = value;
        }

        
        public void selectRoer (ErrorResult value) {
            this.roer = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRorj(null);
                            
        }

        
  
        
        public RejectResult getRorj () {
            return this.rorj;
        }

        public boolean isRorjSelected () {
            return this.rorj != null;
        }

        private void setRorj (RejectResult value) {
            this.rorj = value;
        }

        
        public void selectRorj (RejectResult value) {
            this.rorj = value;
            
                    setRoiv_cmip_event_report(null);
                
                    setRoiv_cmip_confirmed_event_report(null);
                
                    setRoiv_cmip_get(null);
                
                    setRoiv_cmip_set(null);
                
                    setRoiv_cmip_confirmed_set(null);
                
                    setRoiv_cmip_action(null);
                
                    setRoiv_cmip_confirmed_action(null);
                
                    setRors_cmip_confirmed_event_report(null);
                
                    setRors_cmip_get(null);
                
                    setRors_cmip_confirmed_set(null);
                
                    setRors_cmip_confirmed_action(null);
                
                    setRoer(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_MessageChoiceType;
        }

        private static IASN1PreparedElementData preparedData_MessageChoiceType = CoderFactory.getInstance().newPreparedElementData(MessageChoiceType.class);

    }

                
        @ASN1Element ( name = "message", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MessageChoiceType message = null;
                
  
        
        public InvokeIDType getInvoke_id () {
            return this.invoke_id;
        }

        

        public void setInvoke_id (InvokeIDType value) {
            this.invoke_id = value;
        }
        
  
        
        public MessageChoiceType getMessage () {
            return this.message;
        }

        

        public void setMessage (MessageChoiceType value) {
            this.message = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DataApdu.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            