/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package org.universAAL.lddi.lib.ieeex73std.x73.p20601;
//

// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.universAAL.lddi.lib.ieeex73std.org.bn.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.constraints.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.coders.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.types.*;

@ASN1PreparedElement
@ASN1Sequence(name = "RegCertData", isSet = false)
public class RegCertData implements IASN1PreparedElement {

	@ASN1Element(name = "auth-body-and-struc-type", isOptional = false, hasTag = false, hasDefaultValue = false)

	private AuthBodyAndStrucType auth_body_and_struc_type = null;

	@ASN1Any(name = "")

	@ASN1Element(name = "auth-body-data", isOptional = false, hasTag = false, hasDefaultValue = false)

	private byte[] auth_body_data = null;

	public AuthBodyAndStrucType getAuth_body_and_struc_type() {
		return this.auth_body_and_struc_type;
	}

	public void setAuth_body_and_struc_type(AuthBodyAndStrucType value) {
		this.auth_body_and_struc_type = value;
	}

	public byte[] getAuth_body_data() {
		return this.auth_body_data;
	}

	public void setAuth_body_data(byte[] value) {
		this.auth_body_data = value;
	}

	public void initWithDefaults() {

	}

	private static IASN1PreparedElementData preparedData = CoderFactory.getInstance()
			.newPreparedElementData(RegCertData.class);

	public IASN1PreparedElementData getPreparedData() {
		return preparedData;
	}

}
