/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package org.universAAL.lddi.lib.ieeex73std.x73.p20601;
//

// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net
// Any modifications to this file will be lost upon recompilation of the source ASN.1.
//

import org.universAAL.lddi.lib.ieeex73std.org.bn.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.annotations.constraints.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.coders.*;
import org.universAAL.lddi.lib.ieeex73std.org.bn.types.*;

@ASN1PreparedElement
@ASN1Sequence(name = "SegmEntryElem", isSet = false)
public class SegmEntryElem implements IASN1PreparedElement {

	@ASN1Element(name = "class-id", isOptional = false, hasTag = false, hasDefaultValue = false)

	private OID_Type class_id = null;

	@ASN1Element(name = "metric-type", isOptional = false, hasTag = false, hasDefaultValue = false)

	private TYPE metric_type = null;

	@ASN1Element(name = "handle", isOptional = false, hasTag = false, hasDefaultValue = false)

	private HANDLE handle = null;

	@ASN1Element(name = "attr-val-map", isOptional = false, hasTag = false, hasDefaultValue = false)

	private AttrValMap attr_val_map = null;

	public OID_Type getClass_id() {
		return this.class_id;
	}

	public void setClass_id(OID_Type value) {
		this.class_id = value;
	}

	public TYPE getMetric_type() {
		return this.metric_type;
	}

	public void setMetric_type(TYPE value) {
		this.metric_type = value;
	}

	public HANDLE getHandle() {
		return this.handle;
	}

	public void setHandle(HANDLE value) {
		this.handle = value;
	}

	public AttrValMap getAttr_val_map() {
		return this.attr_val_map;
	}

	public void setAttr_val_map(AttrValMap value) {
		this.attr_val_map = value;
	}

	public void initWithDefaults() {

	}

	private static IASN1PreparedElementData preparedData = CoderFactory.getInstance()
			.newPreparedElementData(SegmEntryElem.class);

	public IASN1PreparedElementData getPreparedData() {
		return preparedData;
	}

}
