/*
    Copyright 2007-2014 TSB, http://www.tsbtecnologias.es
    Technologies for Health and Well-being - Valencia, Spain

    See the NOTICE file distributed with this work for additional
    information regarding copyright ownership

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "ApduType" )
    public class ApduType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "aarq", isOptional =  false , hasTag =  true, tag = 57856 , hasDefaultValue =  false  )
    
	private AarqApdu aarq = null;
                
  
        @ASN1Element ( name = "aare", isOptional =  false , hasTag =  true, tag = 58112 , hasDefaultValue =  false  )
    
	private AareApdu aare = null;
                
  
        @ASN1Element ( name = "rlrq", isOptional =  false , hasTag =  true, tag = 58368 , hasDefaultValue =  false  )
    
	private RlrqApdu rlrq = null;
                
  
        @ASN1Element ( name = "rlre", isOptional =  false , hasTag =  true, tag = 58624 , hasDefaultValue =  false  )
    
	private RlreApdu rlre = null;
                
  
        @ASN1Element ( name = "abrt", isOptional =  false , hasTag =  true, tag = 58880 , hasDefaultValue =  false  )
    
	private AbrtApdu abrt = null;
                
  
        @ASN1Element ( name = "prst", isOptional =  false , hasTag =  true, tag = 59136 , hasDefaultValue =  false  )
    
	private PrstApdu prst = null;
                
  
        
        public AarqApdu getAarq () {
            return this.aarq;
        }

        public boolean isAarqSelected () {
            return this.aarq != null;
        }

        private void setAarq (AarqApdu value) {
            this.aarq = value;
        }

        
        public void selectAarq (AarqApdu value) {
            this.aarq = value;
            
                    setAare(null);
                
                    setRlrq(null);
                
                    setRlre(null);
                
                    setAbrt(null);
                
                    setPrst(null);
                            
        }

        
  
        
        public AareApdu getAare () {
            return this.aare;
        }

        public boolean isAareSelected () {
            return this.aare != null;
        }

        private void setAare (AareApdu value) {
            this.aare = value;
        }

        
        public void selectAare (AareApdu value) {
            this.aare = value;
            
                    setAarq(null);
                
                    setRlrq(null);
                
                    setRlre(null);
                
                    setAbrt(null);
                
                    setPrst(null);
                            
        }

        
  
        
        public RlrqApdu getRlrq () {
            return this.rlrq;
        }

        public boolean isRlrqSelected () {
            return this.rlrq != null;
        }

        private void setRlrq (RlrqApdu value) {
            this.rlrq = value;
        }

        
        public void selectRlrq (RlrqApdu value) {
            this.rlrq = value;
            
                    setAarq(null);
                
                    setAare(null);
                
                    setRlre(null);
                
                    setAbrt(null);
                
                    setPrst(null);
                            
        }

        
  
        
        public RlreApdu getRlre () {
            return this.rlre;
        }

        public boolean isRlreSelected () {
            return this.rlre != null;
        }

        private void setRlre (RlreApdu value) {
            this.rlre = value;
        }

        
        public void selectRlre (RlreApdu value) {
            this.rlre = value;
            
                    setAarq(null);
                
                    setAare(null);
                
                    setRlrq(null);
                
                    setAbrt(null);
                
                    setPrst(null);
                            
        }

        
  
        
        public AbrtApdu getAbrt () {
            return this.abrt;
        }

        public boolean isAbrtSelected () {
            return this.abrt != null;
        }

        private void setAbrt (AbrtApdu value) {
            this.abrt = value;
        }

        
        public void selectAbrt (AbrtApdu value) {
            this.abrt = value;
            
                    setAarq(null);
                
                    setAare(null);
                
                    setRlrq(null);
                
                    setRlre(null);
                
                    setPrst(null);
                            
        }

        
  
        
        public PrstApdu getPrst () {
            return this.prst;
        }

        public boolean isPrstSelected () {
            return this.prst != null;
        }

        private void setPrst (PrstApdu value) {
            this.prst = value;
        }

        
        public void selectPrst (PrstApdu value) {
            this.prst = value;
            
                    setAarq(null);
                
                    setAare(null);
                
                    setRlrq(null);
                
                    setRlre(null);
                
                    setAbrt(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ApduType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            