
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AttrValMapEntry", isSet = false )
    public class AttrValMapEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "attribute-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type attribute_id = null;
                
  
        @ASN1Element ( name = "attribute-len", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 attribute_len = null;
                
  
        
        public OID_Type getAttribute_id () {
            return this.attribute_id;
        }

        

        public void setAttribute_id (OID_Type value) {
            this.attribute_id = value;
        }
        
  
        
        public INT_U16 getAttribute_len () {
            return this.attribute_len;
        }

        

        public void setAttribute_len (INT_U16 value) {
            this.attribute_len = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AttrValMapEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            