
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AuthBodyAndStrucType", isSet = false )
    public class AuthBodyAndStrucType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "auth-body", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AuthBody auth_body = null;
                
  
        @ASN1Element ( name = "auth-body-struc-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AuthBodyStrucType auth_body_struc_type = null;
                
  
        
        public AuthBody getAuth_body () {
            return this.auth_body;
        }

        

        public void setAuth_body (AuthBody value) {
            this.auth_body = value;
        }
        
  
        
        public AuthBodyStrucType getAuth_body_struc_type () {
            return this.auth_body_struc_type;
        }

        

        public void setAuth_body_struc_type (AuthBodyStrucType value) {
            this.auth_body_struc_type = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AuthBodyAndStrucType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            