
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AVA_Type", isSet = false )
    public class AVA_Type implements IASN1PreparedElement {
            
        @ASN1Element ( name = "attribute-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type attribute_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "attribute-value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] attribute_value = null;
                
  
        
        public OID_Type getAttribute_id () {
            return this.attribute_id;
        }

        

        public void setAttribute_id (OID_Type value) {
            this.attribute_id = value;
        }
        
  
        
        public byte[] getAttribute_value () {
            return this.attribute_value;
        }

        

        public void setAttribute_value (byte[] value) {
            this.attribute_value = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AVA_Type.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            