
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "BatMeasure", isSet = false )
    public class BatMeasure implements IASN1PreparedElement {
            
        @ASN1Element ( name = "value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type value = null;
                
  
        @ASN1Element ( name = "unit", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type unit_ = null;
                
  
        
        public FLOAT_Type getValue () {
            return this.value;
        }

        

        public void setValue (FLOAT_Type value) {
            this.value = value;
        }
        
  
        
        public OID_Type getUnit_ () {
            return this.unit_;
        }

        

        public void setUnit_ (OID_Type value) {
            this.unit_ = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(BatMeasure.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            