
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ManufSpecAssociationInformation", isSet = false )
    public class ManufSpecAssociationInformation implements IASN1PreparedElement {
            
        @ASN1Element ( name = "data-proto-id-ext", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UuidIdent data_proto_id_ext = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "data-proto-info-ext", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] data_proto_info_ext = null;
                
  
        
        public UuidIdent getData_proto_id_ext () {
            return this.data_proto_id_ext;
        }

        

        public void setData_proto_id_ext (UuidIdent value) {
            this.data_proto_id_ext = value;
        }
        
  
        
        public byte[] getData_proto_info_ext () {
            return this.data_proto_info_ext;
        }

        

        public void setData_proto_info_ext (byte[] value) {
            this.data_proto_info_ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ManufSpecAssociationInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            