
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "SampleType", isSet = false )
    public class SampleType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "sample-size", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 sample_size = null;
                
    
        @ASN1Element ( name = "significant-bits", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 significant_bits = null;
                
  
        
        public INT_U8 getSample_size () {
            return this.sample_size;
        }

        

        public void setSample_size (INT_U8 value) {
            this.sample_size = value;
        }
        
  
        
        public INT_U8 getSignificant_bits () {
            return this.significant_bits;
        }

        

        public void setSignificant_bits (INT_U8 value) {
            this.significant_bits = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SampleType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            