
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ScanReportInfoMPGrouped", isSet = false )
    public class ScanReportInfoMPGrouped implements IASN1PreparedElement {
            
        @ASN1Element ( name = "data-req-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 data_req_id = null;
                
  
        @ASN1Element ( name = "scan-report-no", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 scan_report_no = null;
                
  
@ASN1SequenceOf( name = "scan-per-grouped", isSetOf = false ) 

    
        @ASN1Element ( name = "scan-per-grouped", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<ScanReportPerGrouped>  scan_per_grouped = null;
                
  
        
        public INT_U16 getData_req_id () {
            return this.data_req_id;
        }

        

        public void setData_req_id (INT_U16 value) {
            this.data_req_id = value;
        }
        
  
        
        public INT_U16 getScan_report_no () {
            return this.scan_report_no;
        }

        

        public void setScan_report_no (INT_U16 value) {
            this.scan_report_no = value;
        }
        
  
        
        public java.util.Collection<ScanReportPerGrouped>  getScan_per_grouped () {
            return this.scan_per_grouped;
        }

        

        public void setScan_per_grouped (java.util.Collection<ScanReportPerGrouped>  value) {
            this.scan_per_grouped = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ScanReportInfoMPGrouped.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            