
package x73.p20601;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ScanReportInfoVar", isSet = false )
    public class ScanReportInfoVar implements IASN1PreparedElement {
            
        @ASN1Element ( name = "data-req-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DataReqId data_req_id = null;
                
  
        @ASN1Element ( name = "scan-report-no", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 scan_report_no = null;
                
  
@ASN1SequenceOf( name = "obs-scan-var", isSetOf = false ) 

    
        @ASN1Element ( name = "obs-scan-var", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<ObservationScan>  obs_scan_var = null;
                
  
        
        public DataReqId getData_req_id () {
            return this.data_req_id;
        }

        

        public void setData_req_id (DataReqId value) {
            this.data_req_id = value;
        }
        
  
        
        public INT_U16 getScan_report_no () {
            return this.scan_report_no;
        }

        

        public void setScan_report_no (INT_U16 value) {
            this.scan_report_no = value;
        }
        
  
        
        public java.util.Collection<ObservationScan>  getObs_scan_var () {
            return this.obs_scan_var;
        }

        

        public void setObs_scan_var (java.util.Collection<ObservationScan>  value) {
            this.obs_scan_var = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ScanReportInfoVar.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            